// <auto-generated />
using System;
using HandsOnEFCodeFirst_Demo2.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandsOnEFCodeFirst_Demo2.Migrations
{
    [DbContext(typeof(MovieDBContext))]
    [Migration("20250627071308_CrateBookingTable")]
    partial class CrateBookingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandsOnEFCodeFirst_Demo2.Entities.Booking", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(5)
                        .HasColumnType("char");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("Date");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.HasIndex("MovieId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("HandsOnEFCodeFirst_Demo2.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Genre")
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("title");

                    b.HasKey("MovieId");

                    b.ToTable("tbl_movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.8m,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            Rating = 9.2m,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Quentin Tarantino",
                            Genre = "Crime",
                            Rating = 8.9m,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 4,
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            Rating = 9.3m,
                            ReleaseDate = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            MovieId = 5,
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            Rating = 8.6m,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            MovieId = 6,
                            Director = "Bong Joon-ho",
                            Genre = "Thriller",
                            Rating = 8.6m,
                            ReleaseDate = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Parasite"
                        },
                        new
                        {
                            MovieId = 7,
                            Director = "Ridley Scott",
                            Genre = "Action",
                            Rating = 8.5m,
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gladiator"
                        },
                        new
                        {
                            MovieId = 8,
                            Director = "James Cameron",
                            Genre = "Romance",
                            Rating = 7.8m,
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        },
                        new
                        {
                            MovieId = 9,
                            Director = "Lana Wachowski",
                            Genre = "Sci-Fi",
                            Rating = 8.7m,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 10,
                            Director = "Anthony Russo",
                            Genre = "Superhero",
                            Rating = 8.4m,
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            MovieId = 11,
                            Director = "Todd Phillips",
                            Genre = "Drama",
                            Rating = 8.5m,
                            ReleaseDate = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Joker"
                        },
                        new
                        {
                            MovieId = 12,
                            Director = "Robert Zemeckis",
                            Genre = "Drama",
                            Rating = 8.8m,
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            MovieId = 13,
                            Director = "David Fincher",
                            Genre = "Drama",
                            Rating = 8.8m,
                            ReleaseDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            MovieId = 14,
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            Rating = 9.0m,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 15,
                            Director = "Hayao Miyazaki",
                            Genre = "Animation",
                            Rating = 8.6m,
                            ReleaseDate = new DateTime(2001, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        });
                });

            modelBuilder.Entity("HandsOnEFCodeFirst_Demo2.Entities.Booking", b =>
                {
                    b.HasOne("HandsOnEFCodeFirst_Demo2.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
